//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoXUETA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public string date_create { get; set; }
        public int vid_texnika_id { get; set; }
        public string model_texnika { get; set; }
        public string problem_description { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string midllename { get; set; }
        public string phone_number { get; set; }
        public int status_id { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Vid_texnika Vid_texnika { get; set; }
    }
}
