//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoXUETA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string midllename { get; set; }
        public string phone { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int post_id { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
